2020:03:26 17:19:53:501823 ~ Traceback (most recent call last):
  File "C:\SDK\Anaconda3\lib\site-packages\pydebugger\debug.py", line 222, in read_config
    data = self.cfg.get(section, option)
  File "C:\SDK\Anaconda3\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\SDK\Anaconda3\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'DEBUG'

2020:03:26 17:19:55:046954 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:03:26 17:19:56:772160 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:03:26 17:19:58:463318 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:03:26 17:19:59:967460 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:03:26 17:20:02:748941 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 732, in commit
    if 'https:' in host or 'http:' in host or 'ssh:' in host or 'git:' in host:
TypeError: argument of type 'bool' is not iterable

